### Part A

In [1]:
import numpy as np

### Array that starts from the integer 1, ends at 20, incremented by 3

In [2]:
array = np.arange(1, 21, 3)
print(array)

[ 1  4  7 10 13 16 19]


### A new array of shape 3 with random numbers between 0 and 1

In [3]:
random_array = np.random.rand(1,3)
print(random_array)

[[0.23916503 0.44201514 0.19875736]]


### A 2 D array [[10,20,45], [30,12,16], [42,17,56]] and performs the following operations: 
         
#### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
# Create a 2D array
array_2d = np.array([[10, 20, 45],
                   [30, 12, 16],
                   [42, 17, 56]])

print("Original 2D Array:\n", array_2d)

# Slice the 2D array to get the first two rows
slice_first_two_rows = array_2d[:2, :]
print("\nFirst two rows:\n", slice_first_two_rows)

# Slice the 2D array to get the last two rows
slice_last_two_rows = array_2d[1:, :]
print("\nLast two rows:\n", slice_last_two_rows)

Original 2D Array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows:
 [[10 20 45]
 [30 12 16]]

Last two rows:
 [[30 12 16]
 [42 17 56]]


###  Two 2x2 arrays and demonstrated how to stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [5]:
# Two 2x2 arrays
array1 = np.array([[1, 2],
                 [3, 4]])

array2 = np.array([[5, 6],
                 [7, 8]])

print("Array 1:\n", array1)
print("Array 2:\n", array2)

# Stack the elements vertically
stacked_vertical = np.vstack((array1, array2))
print("\nVertically stacked array:\n", stacked_vertical)

# Stack the elements horizontally
stacked_horizontal = np.hstack((array1, array2))
print("\nHorizontally stacked array:\n", stacked_horizontal)

# Split the vertically stacked array into two smaller arrays
split_vertical_arrays = np.vsplit(stacked_vertical, 2)
print("\nSplitting vertically stacked array into two:\n", split_vertical_arrays)

# Split the horizontally stacked array into two smaller arrays
split_horizontal_arrays = np.hsplit(stacked_horizontal, 2)
print("\nSplitting horizontally stacked array into two:\n", split_horizontal_arrays)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]

Splitting vertically stacked array into two:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Splitting horizontally stacked array into two:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


### multiply these matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])
#### Demonstrated not possible multiply

In [6]:
# Define matrices X and Y
X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

print("Matrix X:\n", X)
print("Shape of X:", X.shape)
print("\nMatrix Y:\n", Y)
print("Shape of Y:", Y.shape)

try:
    # The number of columns in X (3) is equal to the number of rows in Y (3). Therefore, it is possible 
    result_xy = X @ Y
    print("Result of X @ Y:\n", result_xy)

except ValueError as e:
    print(f"Cannot perform X @ Y: {e}")


#Demonstration when it is not possible to multiply matrices
z = np.array([[1, 2],
            [3, 4]])
print("\nMatrix Z:\n", z)
print("Shape of Z:", z.shape)

try:
    # The number of columns in X (3) is equal to the number of rows in Z (2). Therefore, it is not possible 
    result_xz = X @ z
    print("Result of X @ Z:\n", result_xz)
except ValueError as e:
    print(f"Cannot perform X @ Z: {e}")

Matrix X:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Shape of X: (3, 3)

Matrix Y:
 [[4 2]
 [6 2]
 [4 2]]
Shape of Y: (3, 2)
Result of X @ Y:
 [[70 28]
 [70 30]
 [60 26]]

Matrix Z:
 [[1 2]
 [3 4]]
Shape of Z: (2, 2)
Cannot perform X @ Z: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


### Two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
         
#### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [7]:
# Define two arrays
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Vector x:", x)
print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)

# Reshape vector x to a matrix of size (3,1)
x_reshaped = x.reshape(3, 1)
print("\nVector x after reshaping to (3,1):\n", x_reshaped)
print("Shape of reshaped x:", x_reshaped.shape)
print("Number of dimensions of reshaped x:", x_reshaped.ndim)

# Reshape vector y to a matrix of size (3,1)
y_reshaped = y.reshape(3, 1)
print("\nVector y after reshaping to (3,1):\n", y_reshaped)
print("Shape of reshaped y:", y_reshaped.shape)
print("Number of dimensions of reshaped y:", y_reshaped.ndim)

Vector x: [ 2 -1 -8]
Shape of vector x: (3,)
Number of dimensions of vector x: 1

Vector x after reshaping to (3,1):
 [[ 2]
 [-1]
 [-8]]
Shape of reshaped x: (3, 1)
Number of dimensions of reshaped x: 2

Vector y after reshaping to (3,1):
 [[ 3]
 [ 1]
 [-2]]
Shape of reshaped y: (3, 1)
Number of dimensions of reshaped y: 2


#### Demonstration of how does broadcasting work with example of 3 x 3 matrix subtraction and multiplication.

In [8]:
# Create a 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

scalar = 10
vector_row = np.array([1, 0, 1])
vector_col = np.array([[1], [2], [3]])

print("Original 3x3 Matrix:\n", matrix_3x3)

# Broadcasting with a scalar (subtraction)
subtracted_matrix_scalar = matrix_3x3 - scalar
print("\nMatrix after subtracting scalar (10):\n", subtracted_matrix_scalar)

# Broadcasting with a scalar (multiplication)
multiplied_matrix_scalar = matrix_3x3 * scalar
print("\nMatrix after multiplying by scalar (10):\n", multiplied_matrix_scalar)

# Broadcasting with a row vector (subtraction)
# The row vector [1, 0, 1] is broadcast across each row of the matrix.
subtracted_matrix_row_vector = matrix_3x3 - vector_row
print("\nMatrix after subtracting row vector ([1, 0, 1]):\n", subtracted_matrix_row_vector)

# Broadcasting with a row vector (multiplication)
multiplied_matrix_row_vector = matrix_3x3 * vector_row
print("\nMatrix after multiplying by row vector ([1, 0, 1]):\n", multiplied_matrix_row_vector)

# Broadcasting with a column vector (subtraction)
# The column vector [[1], [2], [3]] is broadcast across each column of the matrix.
subtracted_matrix_col_vector = matrix_3x3 - vector_col
print("\nMatrix after subtracting column vector ([[1], [2], [3]]):\n", subtracted_matrix_col_vector)

# Broadcasting with a column vector (multiplication)
multiplied_matrix_col_vector = matrix_3x3 * vector_col
print("\nMatrix after multiplying by column vector ([[1], [2], [3]]):\n", multiplied_matrix_col_vector)

Original 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix after subtracting scalar (10):
 [[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]

Matrix after multiplying by scalar (10):
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Matrix after subtracting row vector ([1, 0, 1]):
 [[0 2 2]
 [3 5 5]
 [6 8 8]]

Matrix after multiplying by row vector ([1, 0, 1]):
 [[1 0 3]
 [4 0 6]
 [7 0 9]]

Matrix after subtracting column vector ([[1], [2], [3]]):
 [[0 1 2]
 [2 3 4]
 [4 5 6]]

Matrix after multiplying by column vector ([[1], [2], [3]]):
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


# Overview of Common Graphs

## Line Graph  
Displays information as a series of data points connected by straight line segments.  

## Bar Graph  
Presents categorical data with rectangular bars whose heights or lengths are proportional to the values they represent.  

## Scatter Plot  
Uses Cartesian coordinates to display values for typically two variables for a set of data.  

## Histogram  
Represents the distribution of numerical data, where the height of the bar indicates the frequency of data points within a given range.  

## Pie Chart  
A circular statistical graphic, divided into slices to illustrate numerical proportion.  

### Part - B

#### determine number of solutions using linear equations

In [9]:

# matrix A and target vector b
A1 = np.array([
    [2, 3, -4],
    [1, -4, 0]
])
b1 = np.array([6, 8])

# Use numpy.linalg.lstsq to find the least-squares solution
x_sol1, residuals1, rank1, s1 = np.linalg.lstsq(A1, b1, rcond=None)
print("Least-squares solution (system 1):", x_sol1)
print("Residuals:", residuals1)
print("Rank of matrix A:", rank1)

# Number of variables
number_vars1 = A1.shape[1]
print("Number of variables in system 1:", number_vars1)
if rank1 < number_vars1:
    print("System 1 has infinitely many solutions (underdetermined).")
elif rank1 == number_vars1:
    print("System 1 has a unique solution.")
else:
    print("System 1 has no solution.")

# For the second system: 3y1 - 4y2 + 5y3 = 10, -y1 + 2y2 - 4y3 = 8
A2 = np.array([
    [3, -4, 5],
    [-1, 2, -4]
])
b2 = np.array([10, 8])

y_sol2, residuals2, rank2, s2 = np.linalg.lstsq(A2, b2, rcond=None)
print("Least-squares solution (system 1):", y_sol2)
print("Residuals:", residuals2)
print("Rank of matrix B:", rank2)

# Number of variables in the second system
number_vars2 = A2.shape[1]

if rank2 < number_vars2:
    print("System 2 has infinitely many solutions (underdetermined).")
elif rank2 == number_vars2:
    print("System 2 has a unique solution.")
else:
    print("System 2 has no solution.")

Least-squares solution (system 1): [ 1.6692112 -1.5826972 -1.8524173]
Residuals: []
Rank of matrix A: 2
Number of variables in system 1: 3
System 1 has infinitely many solutions (underdetermined).
Least-squares solution (system 1): [ 7.46067416 -4.62921348 -6.17977528]
Residuals: []
Rank of matrix B: 2
System 2 has infinitely many solutions (underdetermined).
